---
- name: Start indy operations
  hosts: minindy
  gather_facts: no
  connection: local
  vars:
    pjroot: "{{ playbook_dir }}"
  vars_files:
    - "./spec.yaml"
    - "./playbooks/ops/opnames.yaml"
  tasks:
    - set_fact:
        TARGET_ENV: "{{ TARGET_ENVIRONMENT }}"
        allops: "{{ mode.split(',')|list }}"
        status_flag: "Success"
        current_location_hash: "{{ hostroot | hash('sha256') }}"

    - set_fact:
        CLINAME: "{{ (indy.netname is defined) | ternary(indy.netname, current_location_hash[:10]+'_cli') }}"
        NETNAME: "{{ (indy.netname is defined) | ternary(indy.netname, current_location_hash[:10]+'_net') }}"

    - name: Set endpoint address to first auto detected IP address 
      set_fact:
        endpoint_address: "{{ ADDRS.split(',')[0] }}"
      when: indy.endpoint_address is undefined

    - name: Set up the endpoint address when configured in spec.yaml
      set_fact:
        endpoint_address: "{{ indy.endpoint_address }}"
      when: indy.endpoint_address is defined

    - name: Setup container_options for appending docker run command
      set_fact:
        container_options: "{{ ( indy.container_options is defined ) | ternary(indy.container_options, '') }}"

    - meta: end_play
      when: allops|length == 0

    - set_fact:
        msgops: "{{ (msgops|default([])) + [OPNAMES[item]] }}"
      with_items: "{{ allops }}"

    - name: "Preparing for the following operations:"
      debug:
        msg: "{{ msgops|join(', ') }}"
      when: msgops|length > 1
      tags: [print_action]

    - name: "Process configuration"
      include_tasks: "playbooks/common/config_apply.yaml"

    - name: Check if external node endpoint exists
      stat: 
        path: "{{ pjroot }}/vars/ext_node_vars.json"
      register: exflag

    - name: "Load external node vars"
      include_vars: "{{ pjroot }}/vars/ext_node_vars.json"
      when: exflag.stat.exists == true

    - name: Do all the requested indy operations
      include_tasks: "playbooks/ops/opwrapper.yaml"
      loop: "{{ allops }}"
      loop_control:
        loop_var: op
      when: status_flag == "Success"
