- name: Check if key vars available
  stat:
    path: "{{ pjroot }}/vars/key_vars.json"
  register: keyflag

- name: "Load key vars"
  when: keyflag.stat.exists == true
  include_vars:
    file: "{{ pjroot }}/vars/key_vars.json"
    name: allkeys

- name: "Load key vars"
  when: keyflag.stat.exists == false
  block:
  - name: Find all user and node private keys
    find:
      paths: "{{ pjroot }}/vars/keyfiles"
      patterns: '*_sk'
      recurse: yes
      file_type: file
    register: privatekeys

  - name: Set all validator keys
    set_fact:
      allkeys: >-
        {{ allkeys | default({}) |
          combine({ item.path.split('/')[-4]: {'pkey':item.path.split('/')[-8:]|join('/'),
          'path':item.path, 'key':item.path.split('/')[-4],
          'org':item.path.split('/')[-6], 'type':item.path.split('/')[-5] }}) }}
    when: item.path.find('/validators/') > 0
    with_items: "{{ privatekeys.files }}"
    no_log: yes

  - name: Produce the key var file
    copy:
      dest: "{{ pjroot }}/vars/key_vars.json"
      content: >-
        {{ allkeys | to_nice_json(indent=2) }}
