---
- name: "Check and pull necessary image {{ image }}:{{ indy.release }}"
  include_tasks: "getimage.yaml"
  loop: "{{ (TARGET_ENV == 'K8SCLASSIC') | ternary(['tools'], ['validator']) }}"
  loop_control:
    loop_var: image
  when: status_flag == "Success"

