---
- name: Set validator image release
  set_fact:
    desiredrelease: "{{ indy.release }}"

- name: Check if the image already exist
  command: >-
    docker images -f reference='alanveloso/indy-{{ image }}:{{ desiredrelease }}' -q
  register: imagestate

- name: Retrieve the image if it does not already exist
  command: >-
    docker pull alanveloso/indy-{{ image }}:{{ desiredrelease }}
  when: imagestate.stdout == ''
  register: result
  
- name: Set the status flag based on the return value
  set_fact:
    status_flag: "{{ (result.rc == 0)|ternary('Success', 'Failure') }}"
  when: imagestate.stdout == ''
