- name: "Running operation:"
  debug:
    msg: "{{ OPNAMES[op] }}"
  tags: [print_action]

- name: "Check peer requirement for the operation"
  when: >-
    'PEER' in PRECONDITIONS[op] and allpeers|length == 0
  block:
  - debug:
      msg: "{{ OPNAMES[op] }} requires peer node available, there is non existing in the current environment."
    tags: [print_action]
  - meta: end_play

- include_tasks: "playbooks/ops/{{ op }}/apply.yaml"
